import { Organization } from "./types";

export const seedOrganizations: Organization[] = [
  {
    id: "1",
    name: "Bread of Life International",
    shortDescription: "Providing food security and discipleship in underserved communities across East Africa.",
    description:
      "Bread of Life International partners with local churches to deliver sustainable food security programs, clean water access, and discipleship training across Kenya, Uganda, and Tanzania. Since 2008, we have served over 40,000 individuals and planted 120 partner churches.",
    category: ["relief", "volunteers"],
    region: "East Africa",
    country: "Kenya",
    type: "nonprofit",
    hiring: false,
    volunteersNeeded: true,
    seekingDonors: true,
    verified: true,
    website: "https://example.com",
    contactEmail: "info@breadoflife.example.com",
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Harvest Workers Network",
    shortDescription: "Mobilizing and equipping short-term and long-term missionaries for unreached people groups.",
    description:
      "Harvest Workers Network trains, places, and supports missionaries serving among the world's least-reached people groups. We partner with local churches and denominational networks to ensure missionaries are well-equipped, accountable, and culturally prepared.",
    category: ["missions", "hiring", "education"],
    region: "Global",
    country: "United States",
    type: "nonprofit",
    hiring: true,
    volunteersNeeded: true,
    seekingDonors: true,
    verified: true,
    website: "https://example.com",
    contactEmail: "connect@harvestworkers.example.com",
    createdAt: "2024-02-10",
  },
  {
    id: "3",
    name: "City Light Church",
    shortDescription: "A multiethnic congregation committed to community transformation in urban centers.",
    description:
      "City Light Church is a multiethnic, multigenerational community located in downtown Atlanta. We are committed to church planting, community development, and raising up the next generation of kingdom leaders. We host weekly community dinners, job training programs, and ESL classes.",
    category: ["church", "volunteers"],
    region: "Southeast USA",
    country: "United States",
    type: "church",
    hiring: false,
    volunteersNeeded: true,
    seekingDonors: false,
    verified: true,
    website: "https://example.com",
    contactEmail: "hello@citylight.example.com",
    createdAt: "2024-03-01",
  },
  {
    id: "4",
    name: "Cornerstone Education Initiative",
    shortDescription: "Building Christ-centered schools and literacy programs in rural Southeast Asia.",
    description:
      "Cornerstone Education Initiative develops and operates faith-based schools and adult literacy programs across rural Myanmar, Laos, and Cambodia. Our curriculum integrates academic excellence with biblical discipleship, serving over 3,000 students annually.",
    category: ["education", "volunteers"],
    region: "Southeast Asia",
    country: "Myanmar",
    type: "nonprofit",
    hiring: true,
    volunteersNeeded: true,
    seekingDonors: true,
    verified: true,
    website: "https://example.com",
    contactEmail: "contact@cornerstoneed.example.com",
    createdAt: "2024-03-18",
  },
  {
    id: "5",
    name: "Covenant Legal Group",
    shortDescription: "Kingdom-minded attorneys offering pro bono services to persecuted Christians worldwide.",
    description:
      "Covenant Legal Group is a network of Christian attorneys providing free legal representation, asylum assistance, and religious freedom advocacy to persecuted believers globally. We believe justice is a kingdom mandate.",
    category: ["relief", "hiring"],
    region: "Global",
    country: "United States",
    type: "nonprofit",
    hiring: true,
    volunteersNeeded: false,
    seekingDonors: true,
    verified: true,
    website: "https://example.com",
    contactEmail: "cases@covenantlegal.example.com",
    createdAt: "2024-04-05",
  },
  {
    id: "6",
    name: "Kingdom Marketplace Alliance",
    shortDescription: "Connecting faith-driven entrepreneurs, investors, and executives for kingdom impact.",
    description:
      "Kingdom Marketplace Alliance is a network of Christian business leaders who integrate their faith with their professional influence. We host quarterly gatherings, a mentorship program, and an annual Kingdom Business Summit.",
    category: ["marketplace", "hiring"],
    region: "North America",
    country: "United States",
    type: "forprofit",
    hiring: false,
    volunteersNeeded: false,
    seekingDonors: false,
    verified: false,
    website: "https://example.com",
    contactEmail: "network@kma.example.com",
    createdAt: "2024-04-22",
  },
];

export const featuredMissions = [
  {
    id: "fm1",
    title: "From War Zone to Worship: A Church Plant in Northern Syria",
    excerpt:
      "How a small team of missionaries established a worshiping community in the middle of ongoing conflict — and what sustains them.",
    body: [
      "In the spring of 2022, a team of four missionaries entered a region of northern Syria that most NGOs had already evacuated. They carried three backpacks, a portable generator, and a conviction that the gospel does not wait for peace.",
      "What they found was a community of roughly 800 displaced families living in bombed-out apartment blocks. Many had been there for three years. Some had converted from Islam in secret, meeting in whispers behind locked doors. The team joined them.",
      "Within six months, what began as informal gatherings had become a recognized worshiping community of over 60 members. They meet on Wednesday evenings in a building that still has no roof on the east side — a tarp covers the gap.",
      '"We do not have cushioned seats or a sound system," one of the lead missionaries explained. "What we have is the presence of God and people who have nothing left to lose — which turns out to be the perfect environment for the kingdom to grow."',
      "The team has since trained four local leaders to continue the work. Two of them are former soldiers. One is a grandmother who teaches the children. The other is a man who spent three years as a prisoner of war and came to faith in his cell.",
      "Harvest Workers Network has committed to supporting this plant through 2026, with plans to expand into two neighboring communities. Their need right now is partners willing to pray consistently and give sacrificially — not just once, but monthly.",
      "\"We don't need heroes,\" the team coordinator said. \"We need people who will show up in prayer the same way we show up here — week after week, in the hard and the dark, trusting that the light is stronger.\"",
    ],
    orgName: "Harvest Workers Network",
    orgId: "2",
    region: "Middle East",
    readingTime: 6,
    publishedAt: "2026-04-10",
  },
  {
    id: "fm2",
    title: "Clean Water, Living Water: The Dual Mission in Uganda",
    excerpt:
      "Bread of Life's water project in Gulu not only transformed health outcomes — it opened 300 doors for the gospel.",
    body: [
      "The Gulu district of northern Uganda sits in a region still recovering from two decades of civil conflict. Clean water access remains one of the most persistent unmet needs — and for Bread of Life International, it became the entry point for something far greater.",
      "In January 2025, the organization completed installation of the district's first community-maintained borehole well system in three villages. It took 14 months, three engineering consultants, and hundreds of volunteer labor hours from the community itself.",
      "By March, childhood waterborne illness rates in the three villages had dropped by 68%. But the team's field director, a Ugandan national named Emmanuel, noticed something else happening.",
      '"When you give a community clean water, you earn the right to sit at their table," Emmanuel said. "And when you sit at the table long enough, they ask you why you came."',
      "Over the following months, that question — why did you come? — opened conversations that led to 300 individuals participating in an introductory discipleship series. Forty-seven of them made public professions of faith. Two home churches have since been planted.",
      "The water project cost approximately $42,000. Bread of Life is currently fundraising for four additional borehole systems in neighboring communities, with a target of completion by end of 2026.",
      "The organization has also begun training local women as water system maintenance technicians — a decision that has had the unexpected effect of dramatically increasing women's standing and voice in village council meetings.",
      '"We did not come to build infrastructure," Emmanuel reflected. "We came to love people into the kingdom. But sometimes love looks like clean water first."',
    ],
    orgName: "Bread of Life International",
    orgId: "1",
    region: "East Africa",
    readingTime: 5,
    publishedAt: "2026-03-28",
  },
  {
    id: "fm3",
    title: "Teaching the Next Generation to Lead with Faith",
    excerpt:
      "Inside Cornerstone's teacher training program — and how investing in educators is multiplying kingdom impact across rural Asia.",
    body: [
      "In rural Myanmar, a teacher is often the most educated person in a village. What they believe shapes what an entire community believes. Cornerstone Education Initiative understood this early — and built their entire strategy around it.",
      "Their teacher training program, launched in 2021, does not just teach pedagogy. It teaches theology, character formation, and what Cornerstone calls 'redemptive presence' — the practice of being genuinely known by and invested in the community you serve.",
      "To date, 87 teachers have completed the full 18-month certification program. They now serve in 34 schools across Myanmar, Laos, and Cambodia. Combined, they teach roughly 4,200 students annually.",
      '"A single faithful teacher stays for years," said Cornerstone\'s program director, Dr. Grace Lwin. "A short-term volunteer comes for two weeks. We decided to invest where the multiplying effect is greatest."',
      "The results have been striking. Schools led by Cornerstone-trained teachers report higher literacy rates, lower dropout rates, and — according to community surveys — significantly higher parental trust in the school system.",
      "But the metrics that matter most to the organization are harder to count. In one village in northern Myanmar, a Cornerstone-trained teacher named Daw Aye has been the only consistent Christian presence in her community for four years. Three families have come to faith through her quiet, patient witness.",
      "Cornerstone is currently seeking six volunteer educators for a six-month placement beginning in September 2026. Applicants must have a teaching credential and a demonstrated commitment to cross-cultural ministry.",
      '"We are not looking for people who want an adventure," Dr. Lwin said with a smile. "We are looking for people who want to stay."',
    ],
    orgName: "Cornerstone Education Initiative",
    orgId: "4",
    region: "Southeast Asia",
    readingTime: 4,
    publishedAt: "2026-03-15",
  },
];

export const newsEvents = [
  {
    id: "ne1",
    type: "event" as const,
    title: "KMAN Network Launch Gathering — Atlanta, GA",
    excerpt:
      "Join founding KMAN members for an evening of vision-casting, connection, and prayer as we officially launch the Kingdom Exchange Mission Network.",
    date: "2026-05-17",
    location: "Atlanta, GA",
    virtual: false,
    tags: ["Launch", "Networking"],
  },
  {
    id: "ne2",
    type: "news" as const,
    title: "Kingdom Exchange Mission Network Goes Live",
    excerpt:
      "After months of development, the KMAN directory is now publicly available — listing verified kingdom-minded organizations across six continents.",
    date: "2026-04-24",
    location: null,
    virtual: null,
    tags: ["Announcement"],
  },
  {
    id: "ne3",
    type: "event" as const,
    title: "Missions Connect Webinar: Vetting & Trust in Charitable Giving",
    excerpt:
      "A free online session covering how donors can evaluate mission organizations, what vetting processes look like, and how KMAN's verification system works.",
    date: "2026-05-29",
    location: "Online",
    virtual: true,
    tags: ["Webinar", "Donors"],
  },
  {
    id: "ne4",
    type: "news" as const,
    title: "Cornerstone Education Initiative Joins as Verified Partner",
    excerpt:
      "Cornerstone Education Initiative has completed full vetting and joins KMAN as a Verified Member, expanding the network's reach into Southeast Asia.",
    date: "2026-04-18",
    location: null,
    virtual: null,
    tags: ["Members", "Southeast Asia"],
  },
  {
    id: "ne5",
    type: "event" as const,
    title: "Kingdom Business Summit 2026",
    excerpt:
      "Kingdom Marketplace Alliance hosts their annual gathering of faith-driven entrepreneurs, investors, and executives. KMAN is a featured partner this year.",
    date: "2026-06-14",
    location: "Dallas, TX",
    virtual: false,
    tags: ["Business", "Networking"],
  },
  {
    id: "ne6",
    type: "news" as const,
    title: "Prayer Wall Coming to KMAN: Submit Requests Starting Now",
    excerpt:
      "KMAN is building a public prayer wall — a place for organizations and individuals to share prayer needs with the network. Submissions open now.",
    date: "2026-04-10",
    location: null,
    virtual: null,
    tags: ["Feature", "Prayer"],
  },
];

export const prayerRequests = [
  {
    id: "pr1",
    title: "Breakthrough for the church plant in northern Syria",
    body: "Please pray for the small worshiping community led by Harvest Workers Network in northern Syria. They are facing pressure from local authorities and need wisdom, protection, and boldness. Pray especially for the four local leaders now carrying the work.",
    region: "Middle East",
    orgName: "Harvest Workers Network",
    anonymous: false,
    postedAt: "2026-04-20",
    prayerCount: 47,
  },
  {
    id: "pr2",
    title: "Funding for four new borehole wells in Uganda",
    body: "Bread of Life International is $38,000 short of their fundraising goal for four new borehole wells in the Gulu district. Please pray that God would move the hearts of donors and that the wells would be completed before the rainy season.",
    region: "East Africa",
    orgName: "Bread of Life International",
    anonymous: false,
    postedAt: "2026-04-17",
    prayerCount: 62,
  },
  {
    id: "pr3",
    title: "Wisdom for a family considering long-term missions",
    body: "A family in our network is prayerfully discerning whether to commit to a three-year placement in Southeast Asia. They have three children under ten. Please pray for clarity, unity as a family, and peace that passes understanding.",
    region: "Southeast Asia",
    orgName: null,
    anonymous: true,
    postedAt: "2026-04-15",
    prayerCount: 89,
  },
  {
    id: "pr4",
    title: "Volunteers for Cornerstone's September teacher placement",
    body: "Cornerstone Education Initiative needs six credentialed educators for a September 2026 placement in Myanmar and Laos. Pray that God would call and prepare the right people — and that barriers of fear would be removed.",
    region: "Southeast Asia",
    orgName: "Cornerstone Education Initiative",
    anonymous: false,
    postedAt: "2026-04-12",
    prayerCount: 34,
  },
  {
    id: "pr5",
    title: "Protection for a persecuted believer in North Africa",
    body: "A believer known to our network has been threatened after their conversion became known to their family. We cannot share more details publicly, but please pray for their safety, their faith, and their family's hearts to be softened.",
    region: "North Africa",
    orgName: null,
    anonymous: true,
    postedAt: "2026-04-08",
    prayerCount: 113,
  },
  {
    id: "pr6",
    title: "KMAN launch: that it would serve and not distract",
    body: "As Kingdom Exchange Mission Network launches publicly, please pray that it would genuinely serve the kingdom — connecting people who need each other, without becoming an end in itself. Pray for wisdom for the team and that God would use this platform for his glory.",
    region: "Global",
    orgName: "Kingdom Exchange Mission Network",
    anonymous: false,
    postedAt: "2026-04-24",
    prayerCount: 28,
  },
];
