import { Organization } from "./types";

// Entries are templates: every field and every badge/flag value is kept.
// Fill in the text fields with real content and the entry appears on the site
// with the same card styling and features. Entries whose name/title is still
// blank are filtered out below so empty cards never render.

const allOrganizations: Organization[] = [
  {
    id: "1",
    name: "",
    shortDescription: "",
    description: "",
    category: ["relief", "volunteers"],
    mountains: ["family", "religion"],
    subcategories: ["water-food-relief", "discipleship-training"],
    region: "",
    country: "",
    type: "nonprofit",
    hiring: false,
    volunteersNeeded: true,
    seekingDonors: true,
    verified: true,
    website: "",
    contactEmail: "",
    createdAt: "",
  },
  {
    id: "2",
    name: "",
    shortDescription: "",
    description: "",
    category: ["missions", "hiring", "education"],
    mountains: ["religion"],
    subcategories: ["evangelism-church-planting", "discipleship-training"],
    region: "",
    country: "",
    type: "nonprofit",
    hiring: true,
    volunteersNeeded: true,
    seekingDonors: true,
    verified: true,
    website: "",
    contactEmail: "",
    createdAt: "",
  },
  {
    id: "3",
    name: "",
    shortDescription: "",
    description: "",
    category: ["church", "volunteers"],
    mountains: ["religion"],
    subcategories: ["discipleship-training"],
    region: "",
    country: "",
    type: "church",
    hiring: false,
    volunteersNeeded: true,
    seekingDonors: false,
    verified: true,
    website: "",
    contactEmail: "",
    createdAt: "",
  },
  {
    id: "4",
    name: "",
    shortDescription: "",
    description: "",
    category: ["education", "volunteers"],
    mountains: ["education"],
    subcategories: ["schools-literacy"],
    region: "",
    country: "",
    type: "nonprofit",
    hiring: true,
    volunteersNeeded: true,
    seekingDonors: true,
    verified: true,
    website: "",
    contactEmail: "",
    createdAt: "",
  },
  {
    id: "5",
    name: "",
    shortDescription: "",
    description: "",
    category: ["relief", "hiring"],
    mountains: ["government"],
    subcategories: ["justice-human-rights"],
    region: "",
    country: "",
    type: "nonprofit",
    hiring: true,
    volunteersNeeded: false,
    seekingDonors: true,
    verified: true,
    website: "",
    contactEmail: "",
    createdAt: "",
  },
  {
    id: "6",
    name: "",
    shortDescription: "",
    description: "",
    category: ["marketplace", "hiring"],
    mountains: ["economy"],
    subcategories: ["business-as-mission"],
    region: "",
    country: "",
    type: "forprofit",
    hiring: false,
    volunteersNeeded: false,
    seekingDonors: false,
    verified: false,
    website: "",
    contactEmail: "",
    createdAt: "",
  },
];

const allFeaturedMissions = [
  {
    id: "fm1",
    title: "",
    excerpt: "",
    body: [] as string[],
    orgName: "",
    orgId: "2",
    region: "",
    readingTime: 0,
    publishedAt: "",
  },
  {
    id: "fm2",
    title: "",
    excerpt: "",
    body: [] as string[],
    orgName: "",
    orgId: "1",
    region: "",
    readingTime: 0,
    publishedAt: "",
  },
  {
    id: "fm3",
    title: "",
    excerpt: "",
    body: [] as string[],
    orgName: "",
    orgId: "4",
    region: "",
    readingTime: 0,
    publishedAt: "",
  },
];

const allNewsEvents = [
  {
    id: "ne1",
    type: "event" as const,
    title: "",
    excerpt: "",
    date: "",
    location: "" as string | null,
    virtual: false as boolean | null,
    tags: [] as string[],
  },
  {
    id: "ne2",
    type: "news" as const,
    title: "",
    excerpt: "",
    date: "",
    location: null as string | null,
    virtual: null as boolean | null,
    tags: [] as string[],
  },
  {
    id: "ne3",
    type: "event" as const,
    title: "",
    excerpt: "",
    date: "",
    location: "" as string | null,
    virtual: true as boolean | null,
    tags: [] as string[],
  },
  {
    id: "ne4",
    type: "news" as const,
    title: "",
    excerpt: "",
    date: "",
    location: null as string | null,
    virtual: null as boolean | null,
    tags: [] as string[],
  },
  {
    id: "ne5",
    type: "event" as const,
    title: "",
    excerpt: "",
    date: "",
    location: "" as string | null,
    virtual: false as boolean | null,
    tags: [] as string[],
  },
  {
    id: "ne6",
    type: "news" as const,
    title: "",
    excerpt: "",
    date: "",
    location: null as string | null,
    virtual: null as boolean | null,
    tags: [] as string[],
  },
];

const allPrayerRequests = [
  {
    id: "pr1",
    title: "",
    body: "",
    region: "",
    orgName: null as string | null,
    anonymous: false,
    postedAt: "",
    prayerCount: 0,
  },
  {
    id: "pr2",
    title: "",
    body: "",
    region: "",
    orgName: null as string | null,
    anonymous: false,
    postedAt: "",
    prayerCount: 0,
  },
  {
    id: "pr3",
    title: "",
    body: "",
    region: "",
    orgName: null as string | null,
    anonymous: true,
    postedAt: "",
    prayerCount: 0,
  },
  {
    id: "pr4",
    title: "",
    body: "",
    region: "",
    orgName: null as string | null,
    anonymous: false,
    postedAt: "",
    prayerCount: 0,
  },
  {
    id: "pr5",
    title: "",
    body: "",
    region: "",
    orgName: null as string | null,
    anonymous: true,
    postedAt: "",
    prayerCount: 0,
  },
  {
    id: "pr6",
    title: "",
    body: "",
    region: "",
    orgName: null as string | null,
    anonymous: false,
    postedAt: "",
    prayerCount: 0,
  },
];

const hasText = (value: string) => value.trim() !== "";

export const seedOrganizations = allOrganizations.filter((o) => hasText(o.name));
export const featuredMissions = allFeaturedMissions.filter((m) => hasText(m.title));
export const newsEvents = allNewsEvents.filter((n) => hasText(n.title));
export const prayerRequests = allPrayerRequests.filter((p) => hasText(p.title));
